Replace webpack/shakapacker with esbuild/jsbundling-rails (#343)
* refactor to esbuild/js-bundling instead of webpack

* fix client side validations

* fix activeadmin javascript - delete image was not working

* alphabetize

* comment

* readme

* procfile

* fix docker-compose

* circleci

* bug for ci

* update comments/readme

* update comments/readme

* binstubs

diff --git a/bin/dev b/bin/dev
--- a/bin/dev
+++ b/bin/dev
@@ -1,2 +1,9 @@
-#!/usr/bin/env ruby
-exec "./bin/rails", "server", *ARGV
+#!/usr/bin/env bash
+set -e
+
+if command -v foreman >/dev/null 2>&1; then
+  exec foreman start -f Procfile.dev "$@"
+fi
+
+echo "foreman is required to run Procfile.dev (gem install foreman or brew install foreman)." >&2
+exit 1
